language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-mean-minimal' ]; then cd .. && eval "mv $currentfolder generator-mean-minimal" && cd generator-mean-minimal; fi

